### ISSUE TITLE
Form Area Hide on Eval

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/vue-form-builder#47]
I want to have the ability to hide a field unless a specific criteria is met in the data model

- [x] Add an inspect box for a FEEL expression
- [x] Add label "Hide If:"
- [x] Description: Hide this control unless the following expression is true
- [x] Run the evaluation in the preview and live form
- [ ] Write Dusk Test to confirm it works

**Comment by danloa** [comment]
@velkymx wouldn't it be better that the Description was "  Hide this control **if**  the following expression is true" instead of   "Hide this control **unless**  the following expression is true" I mean the current behavior is to hide control if the condition is true.

**Comment by tdondich** [comment]
Visibility should be by default showing.  If there is anything in this rule then the visibility should be determined by the boolean returned by expression.  False would mean hidden.  True means it would be visible.  It's only evaluated if something is present.  Otherwise defaults to visible.  Text should reflect this.  Product team should validate this.
